import ko from "knockout";

export function Tag(data = {}) {
    this.id = ko.observable(data.Id ?? null);
    this.name = ko.observable(data.Name ?? "");
    this.tagGroupId = ko.observable(data.TagGroupId ?? null);
}

export function getAllStaticTags() {
  return [
    { Id: 2,   Name: "Phone Call", TagGroupId: 3 },
    { Id: 3,   Name: "SMS", TagGroupId: 3 },
    { Id: 4,   Name: "Information", TagGroupId: 4 },
    { Id: 5,   Name: "Update", TagGroupId: 4 },
    { Id: 6,   Name: "Radio", TagGroupId: 3 },
    { Id: 7,   Name: "Email", TagGroupId: 3 },
    { Id: 8,   Name: "Incident Contact", TagGroupId: 2 },
    { Id: 9,   Name: "Fax", TagGroupId: 3 },
    { Id: 10,  Name: "Police", TagGroupId: 2 },
    { Id: 11,  Name: "Ambulance", TagGroupId: 2 },
    { Id: 12,  Name: "RFS", TagGroupId: 2 },
    { Id: 13,  Name: "FRNSW", TagGroupId: 2 },
    { Id: 14,  Name: "Other", TagGroupId: 2 },
    { Id: 15,  Name: "SES", TagGroupId: 2 },
    { Id: 16,  Name: "Resident", TagGroupId: 2 },
    { Id: 17,  Name: "Contractor", TagGroupId: 2 },
    { Id: 18,  Name: "Council", TagGroupId: 2 },
    { Id: 19,  Name: "Recon", TagGroupId: 2 },
    { Id: 250, Name: "BOM", TagGroupId: 2 },
    { Id: 256, Name: "Incoming", TagGroupId: 4 },
    { Id: 257, Name: "Outgoing", TagGroupId: 4 },
    { Id: 258, Name: "Electricity", TagGroupId: 2 },
    { Id: 259, Name: "Water", TagGroupId: 2 },
    { Id: 260, Name: "Printed", TagGroupId: 3 },
    { Id: 285, Name: "Further Action Required", TagGroupId: 27 },
    { Id: 286, Name: "Call Made", TagGroupId: 27 },
    { Id: 287, Name: "Awaiting Update", TagGroupId: 27 },
    { Id: 288, Name: "Ready To Task", TagGroupId: 27 },
    { Id: 289, Name: "Teams Complete", TagGroupId: 27 },
    { Id: 290, Name: "Reopened", TagGroupId: 27 },
    { Id: 291, Name: "Untasked", TagGroupId: 27 },
    { Id: 292, Name: "Referral Required", TagGroupId: 27 },
    { Id: 294, Name: "Face-to-Face", TagGroupId: 3 },
    { Id: 298, Name: "Gas", TagGroupId: 2 },
    { Id: 307, Name: "Retrieve Equipment", TagGroupId: 27 },
    { Id: 420, Name: "ICEMS", TagGroupId: 3 },
    { Id: 421, Name: "TMC", TagGroupId: 2 },
    { Id: 422, Name: "Handover", TagGroupId: 27 },
    { Id: 423, Name: "Call Needed", TagGroupId: 27 },
    { Id: 424, Name: "Not SES Incident", TagGroupId: 27 },
    { Id: 428, Name: "Backdated", TagGroupId: 4 },
    { Id: 500, Name: "NPWS", TagGroupId: 2 },
    { Id: 501, Name: "Telco", TagGroupId: 2 },
    { Id: 502, Name: "Crane/EWP", TagGroupId: 2 },
    { Id: 503, Name: "Arborist", TagGroupId: 2 },
    { Id: 504, Name: "HAZMAT", TagGroupId: 2 },
    { Id: 505, Name: "RMS", TagGroupId: 2 },
    { Id: 506, Name: "Media", TagGroupId: 27 },
    { Id: 517, Name: "Unavailability", TagGroupId: 4 },
    { Id: 518, Name: "GLR", TagGroupId: 4 },
    { Id: 519, Name: "RCR", TagGroupId: 4 },
    { Id: 520, Name: "VR", TagGroupId: 4 },
    { Id: 521, Name: "FR In Water", TagGroupId: 4 },
    { Id: 522, Name: "FR On Water", TagGroupId: 4 },
    { Id: 523, Name: "Flood/Storm", TagGroupId: 4 },
    { Id: 524, Name: "Support", TagGroupId: 4 },
    { Id: 525, Name: "All Capabilities", TagGroupId: 4 },
    { Id: 526, Name: "CFR", TagGroupId: 4 },
    { Id: 551, Name: "Welfare Check", TagGroupId: 27 }
  ];
}