name: Lint Code Base
on: 
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install modules
        run: npm install
      - name: Lint
        run: npm run lint