name: Publish Dev Preview to Chrome Store
on:
  push:
    branches:
      - '**'
jobs:
  lintandpublish:
    name: Publish Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install modules
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build package
        run: npm run dev
      - name: Chrome extension upload action
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: build/*.zip
          extension-id: ${{ secrets.CHROMESTORE_DEV_ID }}
          client-id: ${{ secrets.CHROMESTORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROMESTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROMESTORE_REFRESH_TOKEN }}
          publish: false
          glob: true